output: main.o message.o
       g++ main.o message.o -o output
main.o main.cpp
     g++  -c main.cpp
     
 message.o message.ccp message.h
      g++ -c message.cpp
      
  clear:
      rm*.o.output
